NagendraT_Assignment_36
KrishnaKTechnocredits/JAVATechnoOct2020 pull request #1191
Opened 2020-12-07 20:00 UTC by NagendraTOct2020

![2](https://user-images.githubusercontent.com/73311088/101398918-cb5d5800-38f4-11eb-9111-9ab8debdf4d2.PNG)
![1](https://user-images.githubusercontent.com/73311088/101398982-e16b1880-38f4-11eb-9be1-b1cda1023961.PNG)

2020-12-08 07:22 UTC, harshvegada requested changes
Logic looks bit complex, 
Code works fine but check below code once

https://github.com/KrishnaKTechnocredits/JAVATechnoOct2020/pull/1190/files

2020-12-09 17:08 UTC, NagendraTOct2020 commented
I have updated the assignment 36 and reduced the complexity of code 


Type a message

2020-12-09 18:56 UTC, harshvegada commented on src/nagendra/array/UnionOfArray.java
> +		int i = -000;
this will consider as 0 only -000 make no sense

2020-12-09 18:56 UTC, harshvegada approved these changes
Code looks Good to me
Good to merge

2020-12-09 18:56 UTC, merged