SurbhiJ_Assignment_10
KrishnaKTechnocredits/JAVATechnoOct2020 pull request #248
Opened 2020-11-03 07:58 UTC by SurbhiJOct20

Added assignment 10

2020-11-03 16:10 UTC, KrishnaKTechnocredits commented on src/surbhi/ClassA.java
> +
Extra blank space is not required.

2020-11-03 16:10 UTC, KrishnaKTechnocredits commented on src/surbhi/ClassA.java
> +
Remove this too

2020-11-03 16:10 UTC, KrishnaKTechnocredits commented on src/surbhi/ClassB.java
> +
Remove this line too

2020-11-03 16:11 UTC, KrishnaKTechnocredits commented on src/surbhi/ClassB.java
> +
Please remove extra blank line

2020-11-03 16:11 UTC, KrishnaKTechnocredits commented on src/surbhi/ClassA.java
> +		ClassA A = new ClassA();
reference variable should be in small letter.

2020-11-03 16:12 UTC, KrishnaKTechnocredits commented on src/surbhi/ClassB.java
> +		System.out.println("m3");
printing statements are wrong. you are in m2 method so why should we print "m3". I can see this mistake everywhere.

2020-11-03 16:15 UTC, KrishnaKTechnocredits requested changes
change the code per suggestions.

2020-11-10 15:08 UTC, harshvegada approved these changes
Looks all the method calling are cover so far, Good job @SurbhiJOct20

2020-11-10 18:05 UTC, merged