BrijeshG_Assignment_28
KrishnaKTechnocredits/JAVATechnoOct2020 pull request #888
Opened 2020-11-25 12:00 UTC by BrijeshGOct2020

![image](https://user-images.githubusercontent.com/73329377/100225222-dfdc4080-2f43-11eb-8d92-274036c24920.png)

2020-11-25 13:28 UTC, harshvegada requested changes
Hi Brijesh,
This scenario can be handle in single loop as well,

check below code.
https://github.com/KrishnaKTechnocredits/JAVATechnoOct2020/pull/887/files

2020-11-25 15:02 UTC, BrijeshGOct2020 commented
Hi @harshvegada,

Thanks for comment. What if my array has 11 elements. I think code #887 will not work in such case. That's why I have used 2 for loop to handle those scenarios.
Let me know your view.

2020-11-25 16:36 UTC, harshvegada commented
I agree with your point @BrijeshGOct2020 , for 12 element that will not work, 
I think we have requirement for array which has length in multiplication of 3, then only that code will work, So either we put condition like below
if(arrat.length % 3 == 0){
    //code logic for triplet sum
} else{
    SOP("Enter valid length array");
}

If there requirement to handle all type of array then i need to check again.

2020-11-26 03:35 UTC, BrijeshGOct2020 commented
Hi @harshvegada ,
Please check and let me know if this logic is correct for all type of arrays.

2020-11-26 14:44 UTC, harshvegada commented on src/brijesh/assignment28/ArrayOperation.java
> +		int[] input4= {20,10};
We cannot consider this as triplet right

2020-11-26 14:44 UTC, harshvegada approved these changes

2020-11-26 14:44 UTC, merged