Ankita_Asgnmnt_29
KrishnaKTechnocredits/JAVATechnoOct2020 pull request #935
Opened 2020-11-26 14:27 UTC by AnkitaDOct2020

![image](https://user-images.githubusercontent.com/73325289/100362502-80ecf900-3021-11eb-8e01-5b8e1249d6db.png)

2020-11-26 17:54 UTC, harshvegada requested changes
Hi @AnkitaDOct2020 
Please take look of this code & update code, acknowledge me if you get idea of this below code
https://github.com/KrishnaKTechnocredits/JAVATechnoOct2020/pull/931/files

2020-11-28 03:08 UTC, harshvegada commented on src/ankita/assignment/array/SecondMaxNumber.java
> +		if (arr[0] > arr[1]) {
Why you applied if condition here?

2020-11-28 03:12 UTC, harshvegada commented on src/ankita/assignment/array/SecondMaxNumber.java
> +			} else if (arr[i] > maxSecond) {
else if (numArr[i] > secondLargest && numArr[i] != largest) {
	secondLargest = numArr[i];
}

2020-11-28 03:12 UTC, harshvegada approved these changes
Code give correct output but you need to put on condition in else if,
Take of this next time

2020-11-28 03:12 UTC, merged

2020-11-30 08:40 UTC, AnkitaDOct2020 commented
> Code give correct output but you need to put on condition in else if,
> Take of this next time

Yes Harsh, will take care of this from next time.