Suvela_coding_exam4
KrishnaKTechnocredits/JAVATechnoOct2020 pull request #947
Opened 2020-11-27 02:50 UTC by SuvelaKoct2020

![exam4_1](https://user-images.githubusercontent.com/71068099/100405346-6c444b80-3089-11eb-9162-0a5b9de79e02.png)
![exam4_2](https://user-images.githubusercontent.com/71068099/100405348-6d757880-3089-11eb-89ab-f8f244fcd0e8.png)

2020-11-27 04:32 UTC, harshvegada requested changes
I don't think so you require two for loops here,
using single loop you can check,

using charAt() you can check, hope you get this hint

2020-11-27 08:58 UTC, SuvelaKoct2020 commented
Please check now. @harshvegada

2020-11-28 03:20 UTC, harshvegada commented on src/suvela/exams/Exam4_2.java
> +	void isStringIdentical(String s, String s2) {
Ideally you should this code
think and then write logic


void isStringIdentical(String s, String s2) {
		System.out.println("given strings are:" + s + "," + s2);
		boolean flag = false;
		if (s.length() == s2.length()) {
			for (int i = 0; i < s.length(); i++) {
				if (s.charAt(i) == s2.charAt(i))
					flag = true;
				else {
					flag = false;
					break;
				}
			}
		}
		if (flag)
			System.out.println("both strings are identical");
		else
			System.out.println("both strings are not identical");
	}

2020-11-28 03:20 UTC, harshvegada approved these changes
more practice require on coding

2020-11-28 03:20 UTC, merged